return {
	"pwntester/octo.nvim",
	cmd = "Octo",
	event = { { event = "BufReadCmd", pattern = "octo://*" } },
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"nvim-tree/nvim-web-devicons",
	},
	keys = {
		{ "<leader>go", "<cmd>Octo<cr>", desc = "Octo" },
		{ "<leader>goi", "<cmd>Octo issue list<cr>", desc = "List issues" },
		{ "<leader>gop", "<cmd>Octo pr list<cr>", desc = "List PRs" },
		{ "<leader>gor", "<cmd>Octo repo view<cr>", desc = "View repo" },
		{ "<leader>gos", "<cmd>Octo search<cr>", desc = "Search" },
	},
	opts = {
		use_local_fs = false,
		enable_builtin = false,
		default_remote = { "upstream", "origin" },
		default_merge_method = "squash",
		ssh_aliases = {},
		picker = "telescope",
		picker_config = {
			use_emojis = true,
		},
		comment_icon = "",
		outdated_icon = "",
		resolved_icon = "",
		reaction_viewer_hint_icon = "",
		user_icon = " ",
		timeline_marker = "",
		timeline_indent = "2",
		right_bubble_delimiter = "",
		left_bubble_delimiter = "",
		github_hostname = "",
		snippet_context_lines = 4,
		gh_cmd = "gh",
		gh_env = {},
		timeout = 5000,
		ui = {
			use_signcolumn = true,
			use_signstatus = true,
		},
		issues = {
			order_by = {
				field = "CREATED_AT",
				direction = "DESC",
			},
		},
		pull_requests = {
			order_by = {
				field = "CREATED_AT",
				direction = "DESC",
			},
			always_select_remote_on_create = false,
		},
		file_panel = {
			size = 10,
			use_icons = true,
		},
		mappings = {
			issue = {
				close_issue = { lhs = "<leader>ic", desc = "close issue" },
				reopen_issue = { lhs = "<leader>io", desc = "reopen issue" },
				list_issues = { lhs = "<leader>il", desc = "list open issues" },
				reload = { lhs = "<C-r>", desc = "reload issue" },
				open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
				copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
				add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
				remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
				create_label = { lhs = "<leader>lc", desc = "create label" },
				add_label = { lhs = "<leader>la", desc = "add label" },
				remove_label = { lhs = "<leader>ld", desc = "remove label" },
				goto_issue = { lhs = "<leader>gi", desc = "navigate to a local repo issue" },
				add_comment = { lhs = "<leader>ca", desc = "add comment" },
				delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
				next_comment = { lhs = "]c", desc = "go to next comment" },
				prev_comment = { lhs = "[c", desc = "go to previous comment" },
				react_hooray = { lhs = "<leader>rp", desc = "add/remove 🎉 reaction" },
				react_heart = { lhs = "<leader>rh", desc = "add/remove ❤️ reaction" },
				react_eyes = { lhs = "<leader>re", desc = "add/remove 👀 reaction" },
				react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove 👍 reaction" },
				react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove 👎 reaction" },
				react_rocket = { lhs = "<leader>rr", desc = "add/remove 🚀 reaction" },
				react_laugh = { lhs = "<leader>rl", desc = "add/remove 😄 reaction" },
				react_confused = { lhs = "<leader>rc", desc = "add/remove 😕 reaction" },
			},
			pull_request = {
				checkout_pr = { lhs = "<leader>po", desc = "checkout PR" },
				merge_pr = { lhs = "<leader>pm", desc = "merge commit PR" },
				squash_and_merge_pr = { lhs = "<leader>psm", desc = "squash and merge PR" },
				rebase_and_merge_pr = { lhs = "<leader>prm", desc = "rebase and merge PR" },
				list_commits = { lhs = "<leader>pc", desc = "list PR commits" },
				list_changed_files = { lhs = "<leader>pf", desc = "list PR changed files" },
				show_pr_diff = { lhs = "<leader>pd", desc = "show PR diff" },
				add_reviewer = { lhs = "<leader>va", desc = "add reviewer" },
				remove_reviewer = { lhs = "<leader>vd", desc = "remove reviewer request" },
				close_issue = { lhs = "<leader>ic", desc = "close PR" },
				reopen_issue = { lhs = "<leader>io", desc = "reopen PR" },
				list_issues = { lhs = "<leader>il", desc = "list open issues" },
				reload = { lhs = "<C-r>", desc = "reload PR" },
				open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
				copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
				goto_file = { lhs = "gf", desc = "go to file" },
				add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
				remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
				create_label = { lhs = "<leader>lc", desc = "create label" },
				add_label = { lhs = "<leader>la", desc = "add label" },
				remove_label = { lhs = "<leader>ld", desc = "remove label" },
				goto_issue = { lhs = "<leader>gi", desc = "navigate to a local repo issue" },
				add_comment = { lhs = "<leader>ca", desc = "add comment" },
				delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
				next_comment = { lhs = "]c", desc = "go to next comment" },
				prev_comment = { lhs = "[c", desc = "go to previous comment" },
				react_hooray = { lhs = "<leader>rp", desc = "add/remove 🎉 reaction" },
				react_heart = { lhs = "<leader>rh", desc = "add/remove ❤️ reaction" },
				react_eyes = { lhs = "<leader>re", desc = "add/remove 👀 reaction" },
				react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove 👍 reaction" },
				react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove 👎 reaction" },
				react_rocket = { lhs = "<leader>rr", desc = "add/remove 🚀 reaction" },
				react_laugh = { lhs = "<leader>rl", desc = "add/remove 😄 reaction" },
				react_confused = { lhs = "<leader>rc", desc = "add/remove 😕 reaction" },
				review_start = { lhs = "<leader>vs", desc = "start a review" },
				review_resume = { lhs = "<leader>vr", desc = "resume a review" },
			},
		},
	},
}
